In [1]:
import json
import ast
import numpy as np
from IPython.display import Image
import pandas as pd
import matplotlib.pyplot as plt
import random
from random import shuffle
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.svm import SVC 
from sklearn.naive_bayes import GaussianNB

In [2]:
data = pd.read_excel("Joint_Data.xlsx", sheet_name = 'Sheet')
data_list = np.asarray(data.values.tolist())

In [3]:
np.random.shuffle(data_list)
X = data_list[:,:32]
Y = data_list[:,32]

In [4]:
X_train = X[:10000,:].astype(float)
Y_train = Y[:10000]
X_test = X[10000:,:].astype(float)
Y_test = Y[10000:]

In [5]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit(X_train)
X_train_1 = X_train.copy()
X_test_1 = X_test.copy()
X_train_1 = imp_mean.transform(X_train_1)
X_test_1 = imp_mean.transform(X_test_1)

In [20]:
dtree_model = DecisionTreeClassifier(max_depth = 15).fit(X_train_1, Y_train) 
dtree_predictions = dtree_model.predict(X_test_1) 
accuracy = dtree_model.score(X_test_1, Y_test)
print(accuracy)
cm = confusion_matrix(Y_test, dtree_predictions)
print(cm)

0.23997134670487105
[[ 4  0  0  2  3  2  0  1  0  1  6  0  0  0 10  0  0  3  3  6]
 [ 2 61  1  7  9  6  0 12  6  3 11  0  1  0 14  2  0  0 14  5]
 [ 0  2  1  1  2  1  0  1  0  0  1  0  0  0  6  0  0  1  0  0]
 [ 3  2  0  9  7  3  0  3  1  3 11  0  1  0 12  0  0  0  3  2]
 [ 2  3  0  9 35  7  0  9  2  1 33  3  0  1 14  0  0  1  7  6]
 [ 2 12  0  4 11 23  0  4 10  4 27  0  0  0 14  0  0  0  5  3]
 [ 0  1  0  0  0  1  0  0  0  1  2  0  0  0  0  0  0  0  2  0]
 [ 3  9  0  3 11  6  0 25  0  2 24  0  0  0 17  0  0  1  4  8]
 [ 1  3  0  2  4  4  0  1  9  4 16  1  0  0  8  0  0  1  3  1]
 [ 1  3  0  1  3  3  0  0  2  9  7  0  0  0  3  0  0  1  0  1]
 [ 3 13  1 13 29 18  0 14  6  5 48  0  0  0 24  0  0  1 10  4]
 [ 0  0  0  3  0  0  0  0  2  0  2  1  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  0  3  0  3  0  0  4  0  1  0  6  0  0  0  1  0]
 [ 0  1  0  0  0  1  0  0  1  1  6  0  0  3  0  0  0  0  0  0]
 [10 28  4  8 16 16  0 17  0  4 25  0  1  1 70  0  0  2 13 12]
 [ 0  0  0  0  0  0  0  0  1  0  0 

In [11]:
svm_model_linear = SVC().fit(X_train_1, Y_train) 
#svm_predictions = svm_model_linear.predict(X_test_1) 
accuracy = svm_model_linear.score(X_test_1, Y_test) 
print(accuracy)

/home/prateek/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.16260744985673353


In [12]:
knn = KNeighborsClassifier(n_neighbors = 9).fit(X_train_1, Y_train) 
accuracy = knn.score(X_test_1, Y_test) 
print(accuracy) 

0.29441260744985676


In [16]:
knn_predictions = knn.predict(X_test_1)  
cm = confusion_matrix(Y_test, knn_predictions) 
print(cm)

[[ 4  5  1  2  2  0  0  5  0  0  3  0  0  0 11  0  0  0  2  6]
 [ 4 79  2  4 12  5  0  7  4  2  6  0  1  0 20  0  0  0  5  3]
 [ 0  2  2  0  0  1  0  1  0  1  2  0  0  0  6  0  0  0  0  1]
 [ 0  3  4 10  8  5  0  9  0  3 10  0  0  0  6  0  0  0  1  1]
 [ 1  8  3  8 51  6  0 12  6  4 19  1  1  0 10  0  0  0  1  2]
 [ 5  6  1  6 18 28  0 11  5  2 24  0  0  0  9  0  0  1  0  3]
 [ 1  0  0  0  2  2  0  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 6  8  2  6 11  4  0 28  1  1 18  0  0  0 23  0  0  0  2  3]
 [ 0  4  0  5  9  3  0  1 13  3 14  0  0  0  5  0  0  0  0  1]
 [ 0  1  1  2  7  2  0  0  1 13  4  0  0  1  2  0  0  0  0  0]
 [ 4 21  3  3 25 14  0 10  5  4 62  0  1  1 26  0  0  2  3  5]
 [ 0  2  0  3  0  0  0  0  1  0  2  0  0  0  0  0  0  0  0  0]
 [ 1  0  2  0  2  0  0  4  0  0  2  0  3  0  5  0  0  2  0  1]
 [ 0  1  0  0  3  1  0  0  0  0  1  0  0  7  0  0  0  0  0  0]
 [15 18  6 12 15  9  1 22  1  3 20  1  1  1 84  0  0  0 10  8]
 [ 0  0  0  0  1  0  0  0  0  0  3  0  0  0  1  1  0  0

In [13]:
gnb = GaussianNB().fit(X_train_1, Y_train) 
gnb_predictions = gnb.predict(X_test_1) 

In [14]:
accuracy = gnb.score(X_test_1, Y_test) 
print (accuracy) 

0.07521489971346705
