In [671]:
import numpy as np
import random
from random import shuffle
from sklearn.model_selection import train_test_split

In [672]:
with open("spambase.data") as file:
    data_array = [line.rstrip('\n') for line in file]

In [673]:
data_array_split = [x.split(',') for x in data_array]
data_array_final=[]
for x in range(len(data_array_split)):
    data_array_final.append([])
    for y in range(len(data_array_split[x])):
        data_array_final[x].append(float(data_array_split[x][y]))

In [674]:
data_array = np.asarray(data_array_final)
X = data_array[:,:data_array.shape[1]-1]
y = np.reshape(np.asarray(data_array[:,data_array.shape[1]-1]), (X.shape[0], 1))

In [675]:
X_temp = np.append(X, y, axis=1)
np.random.seed(0)
np.random.shuffle(X_temp)
print(X_temp)

[[1.000e-01 2.000e-01 1.010e+00 ... 6.690e+02 1.351e+03 1.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 ... 1.000e+00 4.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 ... 4.000e+00 1.500e+01 0.000e+00]
 ...
 [4.300e-01 4.000e-01 3.700e-01 ... 1.780e+02 3.303e+03 1.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 ... 1.200e+01 1.190e+02 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 ... 5.000e+00 9.000e+00 0.000e+00]]


In [676]:
X_train, X_test, y_train, y_test = train_test_split(X_temp[:,:X_temp.shape[1]-1],X_temp[:,X_temp.shape[1]-1], test_size=0.33)

In [677]:
X_stdd = ((X_train-X_train.mean(axis=0))/X_train.std(axis=0))
#print(X_train.mean(axis=0))

y_train = np.reshape(np.asarray(y_train), (np.asarray(y_train).shape[0], 1))
X_stdd = np.hstack((X_stdd, y_train))
X_not_std = np.hstack((X_train, y_train))
print(X_stdd.shape)
print(X_not_std.shape)
X_stdd_test = ((X_test-X_test.mean(axis=0))/X_test.std(axis=0))
y_test = np.reshape(np.asarray(y_test), (np.asarray(y_test).shape[0], 1))
print(X_stdd_test.shape)
print(y_test.shape)

(3082, 58)
(3082, 58)
(1519, 57)
(1519, 1)


In [717]:
#X_stdd_pos = np.empty((0, X_stdd.shape[1]), dtype=float)
#X_stdd_neg = np.empty((0, X_stdd.shape[1]), dtype=float)
X_stdd_pos = np.empty((0, X_not_std.shape[1]), dtype=float)
X_stdd_neg = np.empty((0, X_not_std.shape[1]), dtype=float)
#print(X_not_stdd_pos.shape)
for x_temp in range(X_not_std.shape[0]):
    if y_train[x_temp]==1:
        #print(y_train[x_temp].shape)
        #X_stdd_pos = np.vstack((X_stdd_pos, X_stdd[x_temp,:]))
        X_stdd_pos = np.vstack((X_stdd_pos, X_not_std[x_temp,:]))
        #print(X_stdd_pos)
        #X_stdd_pos[i, :] = np.append(X_stdd_pos[i, :], [y_train[x_temp]])
        
    else:
        #print(y_train[x_temp].shape)
        #X_stdd_neg = np.vstack((X_stdd_neg, X_stdd[x_temp,:]))
        X_stdd_neg = np.vstack((X_stdd_neg, X_not_std[x_temp,:]))
        #print(X_stdd_neg)
        #X_stdd_neg[i, :] = np.append(X_stdd_neg[i, :], [y_train[x_temp]])
#print(X_stdd_pos.shape)
#print(X_stdd_neg.shape)
#print(X_stdd_pos.mean(axis=0))
for i in range(X_stdd_pos.shape[1]-1):
    #temp = (X_stdd.mean(axis=0))[i]
    temp = (X_train.mean(axis=0))[i]
    #print(temp)
    for j in range (X_stdd_pos.shape[0]):
        #print(j)
        if(X_stdd_pos[j][i]<temp):
            X_stdd_pos[j][i] = 0
        else:
            X_stdd_pos[j][i] = 1
    
print(X_stdd_pos.shape)

for i in range(X_stdd_neg.shape[1]-1):
    #temp = (X_stdd.mean(axis=0))[i]
    temp = (X_train.mean(axis=0))[i]
    #print(temp)
    for j in range (X_stdd_neg.shape[0]):
        #print(j)
        if(X_stdd_neg[j][i]<temp):
            X_stdd_neg[j][i] = 0
        else:
            X_stdd_neg[j][i] = 1

print(X_stdd_neg.shape)
X_train_std_bin = np.vstack((X_stdd_pos,X_stdd_neg))
#X_train_std_bin = np.vstack((X_stdd_pos,X_stdd_neg))
print(X_train_std_bin)

(1205, 58)
(1877, 58)
[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 1. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 0.]]


In [679]:
Total_entropy=-((X_stdd_pos.shape[0]/X_train_std_bin.shape[0])*np.log2(X_stdd_pos.shape[0]/X_train_std_bin.shape[0]))-((X_stdd_neg.shape[0]/X_train_std_bin.shape[0])*np.log2(X_stdd_neg.shape[0]/X_train_std_bin.shape[0]))
print(Total_entropy)

0.9654289910397931


In [680]:

def entropy(target_col):#y_train
   
    elements,counts = np.unique(target_col,return_counts = True)
    #print(elements.shape)
    #print(counts)
    entropy = np.sum([(-counts[i]/np.sum(counts))*np.log2(counts[i]/np.sum(counts)) for i in range(len(elements))])
    return entropy
##log2 and log make a difference in entropy calculation
entropy(y_train)

0.9654289910397931

In [681]:
def InfoGain(data,split_attribute_,target_train):
 
    
    #Calculate the entropy of the total dataset

    total_entropy = entropy([target_train]) 
    #print(total_entropy)
    
    ##Calculate the entropy of the dataset
    Vals=np.zeros(2)
    #print(Vals)
    #Calculate the values and the corresponding counts for the split attribute 
    vals,counts= np.unique(split_attribute_,return_counts=True)
    #print("vals:", vals, "counts: ", counts)
    Vals = vals
    #print("Vals:", Vals, "counts: ", counts)
    #for i in range(len(Vals)):
          #  if Vals[i]:
                #print("Found element")
            #else:
                #print(len(Vals))
              #  Vals[i] == 0
            
    
    target_col = []
    target_col_EFones = []
    target_col_EFzeros = []
    #print(split_attribute_.shape[0])
    for j in range(len(split_attribute_)):
        for i in range(len(Vals)):  
            if (Vals[i] == 1 and split_attribute_[j]==Vals[i]):#Ef1
                #print(j)
                #print(vals[i])
                #print(split_attribute_[j])
                #print(target_train[j])
                target_col_EFones.append(target_train[j])
                #print("ones")
            elif (Vals[i] == 0 and split_attribute_[j]==Vals[i]):#Ef0
                #print(j)
                #print(split_attribute_[j,0])
                #print(target_train[j])
                target_col_EFzeros.append(target_train[j])
                #print("zeros")
                #print("y-train value to be appended for entropy target column: ", target_train[j], "and index: ", j)
    
    #print(len(target_col_EFones))
    target_col_EFones = np.reshape(np.asarray(target_col_EFones), (np.asarray(target_col_EFones).shape[0], 1))
    target_col_EFzeros = np.reshape(np.asarray(target_col_EFzeros), (np.asarray(target_col_EFzeros).shape[0], 1))
    #print(target_col_EFones) 
    #print(target_col_EFzeros)            
    
    #Calculate the weighted entropy
    Weighted_Entropy_ones =np.asarray([(counts[0]/np.sum(counts))*entropy(target_col_EFones) ])
    
    
    
    if len(counts)<2:
        
        Weighted_Entropy_zeros =np.asarray([(0/np.sum(counts))*entropy(target_col_EFzeros) ])
    else:
        Weighted_Entropy_zeros =np.asarray([(counts[1]/np.sum(counts))*entropy(target_col_EFzeros) ])
    #print(len(counts))   
    #print(Weighted_Entropy_ones)
    #print(Weighted_Entropy_zeros)
    Weighted_Sum = Weighted_Entropy_ones + Weighted_Entropy_zeros
    #print(Weighted_Sum)
    #Calculate the information gain
    Information_Gain = total_entropy - Weighted_Sum
    print(Information_Gain)
    return Information_Gain

temp = X_train_std_bin[:,0:1]
Y_train_bin = X_train_std_bin[:, -1:]
#print(temp)
InfoGain(X_train_std_bin, temp, Y_train_bin)

[0.02344143]


array([0.02344143])

In [682]:
def ID3(data,originaldata,parent_node_class = None):

    features = {}
    if data.shape[0]>1:
        print("sub data shape: ", data.shape)
        for i in range(data.shape[1]-1):
    #print(X_train_std_bin[:, i].shape)
            features.update( {i : data[:, i]} )
    
    #Define the stopping criteria --> If one of this is satisfied, we want to return a leaf node#
    
    
    #If all target_values have the same value, return this value
    target_train = data[:, -1:]
    #print("feature length: ", len(features))
    
    if len(np.unique(target_train)) <= 1:
        return np.unique(target_train)[0]

    
    #If the dataset is empty, return the mode target feature value in the original dataset
    elif data.shape[0] <= 1:
    #elif len(data) == 0:
        return np.unique(target_train)[np.argmax(np.unique(target_train,return_counts=True)[1])]
        
    
    
    ##determine features of sub_dataset here
    
    
    elif len(features) == 0:
        print(features)
        return parent_node_class
    
    
    
    else:
        # default value for this node --> The mode target feature valu
        parent_node_class = np.unique(target_train)[np.argmax(np.unique(target_train,return_counts=True)[1])]
        
        #Select the feature which best splits the dataset
        
        
        IG_values = [InfoGain(data,features[feature],target_train) for feature in features] #Return the information gain values for the features in the dataset
            
        best_feature_index = np.argmax(IG_values)
        #print("best feature index: ", best_feature_index)
        #print(features[best_feature_index])
        best_feature = features[best_feature_index]
        #print(best_feature)
        
        #Create the tree structure. The root gets the name of the feature (best_feature) with the maximum information
        #gain in the first run
        tree = {best_feature_index:{}}
        
        
        #Remove the feature with the best inforamtion gain from the feature space
        Features = [features[i] for i in features if i != best_feature_index]
        Features = (np.asarray(Features)).T
        #print("Features shape: ", Features.shape)
        
        #Grow a branch under the root node for each possible value of the root node feature
        
        for value in np.unique(best_feature):
            value = value
            #print(value)
            #Split the dataset along the value of the feature with the largest information gain and therwith create sub_datasets
            print("New features number of columns: ", Features.shape)
            if Features.shape[0]==0:
                print("Features are empty")
                sub_data = np.empty((1, 1), dtype=float)
               
            else:
                sub_data = np.empty((0, Features.shape[1]+1), dtype=float)
            #sub_data = []
            
            
            for i in range(len(best_feature)):
                if best_feature[i] == value:
                    #print("Feature i: ", Features[i].shape, "Features: ", Features[i])
                    #print("Target i: " , target_train[i])
                    if Features.shape[0]==0:
                        temp_data = target_train[i]
                    else:
                        temp_data = np.append(Features[i], (target_train[i]))
                    #print("temp data shape: ", temp_data.shape, "temp data for stack in sub data: ", temp_data)
                    #print("sub data shape: ", sub_data.shape)
                    sub_data = np.vstack((sub_data, temp_data))
              
            #print("Sub data: ", sub_data, "Sub data shape: ", sub_data.shape)
            #Call the ID3 algorithm for each of those sub_datasets with the new parameters --> Here the recursion comes in!
            subtree = ID3(sub_data,X_train_std_bin,parent_node_class)
            
            #Add the sub tree, grown from the sub_dataset to the tree under the root node
            print("best feature index: ", best_feature_index, "binary value:", value)
            tree[best_feature_index][value] = subtree
            
        return(tree)    
                

In [683]:
def predict(query,tree,default = 1):
    for key in list(query.keys()):
        if key in list(tree.keys()):
            #2.
            try:
                result = tree[key][query[key]] 
            except:
                return default
  
            #3.
            result = tree[key][query[key]]
            #4.
            if isinstance(result,dict):
                return predict(query,result)

            else:
                return result


In [730]:
def test(data,tree):
 
    queries = {}
    if data.shape[0]>1:
        print("sub data shape: ", data.shape)
        for i in range(data.shape[1]+1):
                #print(i)
                if i < data.shape[1]:
                    queries.update( {i : data[:, i]} )
                else:
                    predicted_array = np.empty((data.shape[0], 1), dtype=float)
                    queries.update( {i : predicted_array} )
    
    for key, value in queries.items() :
        print (key, value)
    
    #for i in range(data.shape[1]):
    np.append(queries[data.shape[1]], predict(queries,tree,1.0))
    #for i in len(queries[data.shape[1]]):
    
    print((queries[data.shape[1]]))
    
    print(np.sum(queries[data.shape[1]] == y_test))
   
    
    fp = 0
    fn = 0
    tn = 0
    tp = 0
    for t in range(len(queries[data.shape[1]])):
        if y_test[t]==0 and queries[data.shape[1]][t]==0:
            tn+=1
        elif y_test[t]==0 and queries[data.shape[1]][t]==1:
            fp+=1
        elif y_test[t]==1 and queries[data.shape[1]][t]==0:
            fn+=1
        else:
            tp+=1
            
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    accuracy = (tp+tn)/(tp+tn+fp+fn)
    f_measure = 2*precision*recall/(precision+recall)
    print(fp, fn, tn, tp)
    print("Precision: ", precision)
    print("Recall: ", recall)
    print("Accuracy: ", accuracy)
    print("F-measure: ", f_measure)

In [731]:
#might need a for loop to go over each feature
#print(X_train_std_bin)


       
#print(len(features))
#for key, value in features.items(): 
 #   print (key, value)
    

tree = ID3(X_train_std_bin,X_train_std_bin)
print("Full tree with nodes: ", tree)
print("Tree's keys: ",tree.keys())
test(X_stdd_test,tree)



sub data shape:  (3082, 58)
[0.02344143]
[0.11606474]
[0.05534655]
[0.19286605]
[0.07288809]
[0.09570594]
[0.57867774]
[0.17449112]
[0.1112945]
[0.0383745]
[0.25255149]
[-0.00697292]
[0.03603535]
[0.00867195]
[0.34217783]
[0.26704455]
[0.12446323]
[0.06391604]
[0.06692131]
[0.49290713]
[0.13242]
[0.28420688]
[0.51519671]
[0.53494029]
[0.67134958]
[0.68414928]
[0.8451414]
[0.54596249]
[0.79950563]
[0.6809089]
[0.82628986]
[0.86279625]
[0.37977417]
[0.61026212]
[0.58786978]
[0.28310098]
[0.39518625]
[0.05275978]
[0.29198359]
[-0.00875216]
[0.85458015]
[0.74378256]
[0.1704981]
[0.4809752]
[0.10353868]
[0.56677999]
[0.10817516]
[0.52015188]
[0.12190028]
[0.04280354]
[0.15392635]
[0.2154658]
[0.41898302]
[0.05407143]
[0.3683893]
[0.22570028]
[0.03362429]
New features number of columns:  (3082, 56)
sub data shape:  (2939, 57)
[0.05017897]
[0.1476365]
[0.06546777]
[0.20354664]
[0.10873142]
[0.11605686]
[0.61225056]
[0.19450115]
[0.13475133]
[0.0766027]
[0.2725069]
[-0.00142307]
[0.05681487]
[

[0.23594522]
[0.04397969]
[0.5641417]
[0.17364145]
[0.30170971]
[0.57569312]
[0.0891517]
[0.07109131]
[0.1388537]
[0.48353354]
[0.09773992]
[0.02007706]
[0.00822204]
[0.04015642]
[0.01646433]
[0.24159224]
[-0.00373553]
[0.29583647]
[-0.00675334]
[-0.00377629]
[0.31969192]
[-0.00880096]
[0.00282823]
[0.00789505]
[0.17402534]
[0.50407491]
[0.2879284]
[0.44105106]
[0.37087428]
[0.24689266]
New features number of columns:  (1281, 45)
sub data shape:  (991, 46)
[0.00967169]
[0.0324487]
[0.02486789]
[0.3650117]
[0.14919649]
[0.09861161]
[0.35569924]
[0.21479786]
[0.08062481]
[0.1600952]
[-0.00479591]
[0.00253499]
[0.07426134]
[0.30984066]
[0.31060267]
[0.06370745]
[0.02044062]
[0.43177738]
[0.10257771]
[0.1730107]
[0.46793436]
[0.08774392]
[0.06984124]
[0.27861854]
[0.44206755]
[0.37168194]
[-0.00989066]
[0.13013424]
[-0.01062412]
[0.24690954]
[0.0426284]
[0.00390478]
[0.43530325]
[0.03213597]
[0.07027614]
[0.47263887]
[0.00420864]
[-0.00219805]
[-0.00340511]
[0.11901466]
[0.47478035]
[0.122

[-0.09504754]
[0.00265643]
[-0.04647937]
[-0.09763773]
[0.01393183]
[-0.09607999]
[0.16440972]
[-0.06552655]
[0.15972525]
[0.14928959]
[-0.03026028]
[-0.0773126]
[0.02337199]
[0.3124293]
[-0.01664672]
[-0.06968855]
[-0.05663711]
[0.06494046]
[-0.09842776]
New features number of columns:  (550, 30)
sub data shape:  (547, 31)
[0.07377728]
[-0.05356926]
[-0.05975747]
[0.00628601]
[-0.1056177]
[-0.10642713]
[-0.06322531]
[-0.01236097]
[-0.02817982]
[0.08119414]
[0.14281207]
[-0.10118715]
[0.00174573]
[-0.04951705]
[-0.1020387]
[-0.01194705]
[-0.10057607]
[0.15987941]
[-0.07001452]
[0.15529581]
[0.14538364]
[-0.03479756]
[-0.08151795]
[0.02656146]
[0.30794092]
[-0.01682011]
[-0.07399777]
[-0.07311391]
[0.04140987]
[-0.10634674]
New features number of columns:  (547, 29)
sub data shape:  (532, 30)
[0.07077177]
[-0.05235742]
[-0.05825671]
[0.01061482]
[-0.09742044]
[-0.09610243]
[-0.06592676]
[-0.02847931]
[-0.0259813]
[0.07340401]
[0.14321824]
[-0.09612467]
[0.00342608]
[-0.0447461]
[-0.0964

[-0.05346074]
[-0.093789]
[0.70627409]
[-0.00364772]
[0.68187757]
New features number of columns:  (26, 8)
sub data shape:  (26, 9)
[-0.26680456]
[-0.26680456]
[-0.0119114]
[-0.05346074]
[-0.093789]
[0.70627409]
[-0.00364772]
[0.68187757]
New features number of columns:  (26, 7)
sub data shape:  (26, 8)
[-0.26680456]
[-0.26680456]
[-0.0119114]
[-0.05346074]
[-0.093789]
[-0.00364772]
[0.68187757]
New features number of columns:  (26, 6)
sub data shape:  (25, 7)
[-0.3303808]
[0.60830866]
[-0.06520098]
[-0.11798779]
[-0.19708379]
[-0.00908799]
New features number of columns:  (25, 5)
sub data shape:  (24, 6)
[-0.31453055]
[-0.05259758]
[-0.09869694]
[-0.18062018]
[-0.0043819]
New features number of columns:  (24, 4)
sub data shape:  (13, 5)
[0.56938047]
[-0.19522897]
[0.12491521]
[-0.19522897]
New features number of columns:  (13, 3)
sub data shape:  (12, 4)
[-0.16451404]
[0.1908745]
[-0.16451404]
New features number of columns:  (12, 2)
sub data shape:  (6, 3)
best feature index:  1 bina

sub data shape:  (41, 20)
[-0.04193256]
[-0.18818618]
[0.64450173]
[0.62625618]
[0.60894647]
[-0.02676152]
[-0.11333461]
[-0.21112146]
[0.002085]
[-0.02676152]
[0.64450173]
[0.65937588]
[0.65937588]
[-0.3220574]
[0.15016636]
[-0.04193256]
[0.64305842]
[0.64450173]
[0.64305842]
New features number of columns:  (41, 18)
sub data shape:  (41, 19)
[-0.04193256]
[-0.18818618]
[0.64450173]
[0.62625618]
[0.60894647]
[-0.02676152]
[-0.11333461]
[-0.21112146]
[0.002085]
[-0.02676152]
[0.64450173]
[0.65937588]
[-0.3220574]
[0.15016636]
[-0.04193256]
[0.64305842]
[0.64450173]
[0.64305842]
New features number of columns:  (41, 17)
sub data shape:  (41, 18)
[-0.04193256]
[-0.18818618]
[0.64450173]
[0.62625618]
[0.60894647]
[-0.02676152]
[-0.11333461]
[-0.21112146]
[0.002085]
[-0.02676152]
[0.64450173]
[-0.3220574]
[0.15016636]
[-0.04193256]
[0.64305842]
[0.64450173]
[0.64305842]
New features number of columns:  (41, 16)
sub data shape:  (40, 17)
[-0.07323314]
[-0.25761771]
[0.57837784]
[0.56188102]

[-0.71463755]
[-0.60690278]
[-0.71463755]
[0.18297732]
[0.18297732]
[0.20063568]
[0.17331378]
[0.18297732]
[0.18297732]
New features number of columns:  (29, 10)
sub data shape:  (27, 11)
[-0.58772482]
[0.17913722]
[0.22853814]
[-0.69738778]
[0.22853814]
[0.19031316]
[0.19031316]
[0.19031316]
[0.19031316]
[0.19031316]
New features number of columns:  (27, 9)
sub data shape:  (26, 10)
best feature index:  2 binary value: 0.0
New features number of columns:  (27, 9)
best feature index:  2 binary value: 1.0
best feature index:  7 binary value: 0.0
New features number of columns:  (29, 10)
sub data shape:  (2, 11)
best feature index:  7 binary value: 1.0
best feature index:  8 binary value: 0.0
best feature index:  0 binary value: 0.0
New features number of columns:  (30, 12)
best feature index:  0 binary value: 1.0
best feature index:  0 binary value: 0.0
New features number of columns:  (31, 13)
best feature index:  0 binary value: 1.0
best feature index:  5 binary value: 0.0
New feature

[0.16041014]
[0.17598144]
[0.18447228]
[0.10375906]
[0.14271929]
[0.18170674]
[0.17598144]
[0.14644961]
[-0.103428]
[0.18447228]
New features number of columns:  (70, 17)
sub data shape:  (69, 18)
[0.18076064]
[0.16842122]
[0.14739868]
[0.17474058]
[0.16842122]
[0.17778655]
[-0.22971054]
[0.16177726]
[0.17778655]
[0.18650404]
[0.10327221]
[0.14739868]
[0.1836656]
[0.17778655]
[0.15113977]
[-0.10111219]
[0.18650404]
New features number of columns:  (69, 16)
sub data shape:  (68, 17)
[0.18567122]
[0.17000286]
[0.15220652]
[0.17963194]
[0.17329274]
[0.17963194]
[-0.22707152]
[0.16316534]
[0.17963194]
[0.10271034]
[0.15220652]
[0.18567122]
[0.17963194]
[0.15220652]
[-0.09875314]
[0.18858557]
New features number of columns:  (68, 15)
sub data shape:  (67, 16)
[0.18772534]
[0.1716145]
[0.15714828]
[0.18151899]
[0.17830008]
[0.18151899]
[-0.22437113]
[0.16457456]
[0.18151899]
[0.10206676]
[0.15327917]
[0.18772534]
[0.18151899]
[0.15327917]
[-0.09635005]
New features number of columns:  (67, 1

[-0.07064243]
[-0.04680663]
[0.16958151]
[-0.16625127]
New features number of columns:  (38, 12)
sub data shape:  (24, 13)
[-0.04053446]
[0.04791755]
[-0.03162668]
[0.07447802]
[0.16395604]
[-0.02787295]
[0.07447802]
[0.07447802]
[0.21758236]
[0.07447802]
[0.19222154]
[-0.05248966]
New features number of columns:  (24, 11)
sub data shape:  (8, 12)
[0.70338805]
[0.81127812]
[0.58170417]
[0.44717165]
[-0.10122748]
[0.]
[0.]
[0.44717165]
[0.44717165]
[-0.10122748]
[0.44717165]
New features number of columns:  (8, 10)
sub data shape:  (8, 11)
[0.70338805]
[0.58170417]
[0.44717165]
[-0.10122748]
[0.]
[0.]
[0.44717165]
[0.44717165]
[-0.10122748]
[0.44717165]
New features number of columns:  (8, 9)
sub data shape:  (7, 10)
[0.73193545]
[0.43454914]
[-0.05743032]
[-0.00931053]
[-0.00931053]
[0.43454914]
[0.43454914]
[-0.05743032]
[0.43454914]
New features number of columns:  (7, 8)
sub data shape:  (6, 9)
[0.45914792]
[-0.01879687]
[-0.01879687]
[0.]
[0.5849625]
[0.5849625]
[-0.01879687]
[0.45

[0.59503752]
[-0.2346159]
[0.43198731]
[0.59503752]
[0.59503752]
New features number of columns:  (19, 19)
sub data shape:  (17, 20)
[0.25724537]
[0.30291637]
[-0.18683934]
[-0.55959598]
[0.28118527]
[0.28118527]
[0.12964113]
[0.23069965]
[-0.55959598]
[0.16764038]
[0.25724537]
[0.30291637]
[0.30291637]
[0.08592951]
[0.30291637]
[0.28118527]
[0.20104612]
[0.30291637]
[0.30291637]
New features number of columns:  (17, 18)
sub data shape:  (16, 19)
[0.2639319]
[-0.1590355]
[-0.53770993]
[0.29088603]
[0.31520511]
[0.16141672]
[0.23383585]
[-0.53770993]
[0.16141672]
[0.29088603]
[0.31520511]
[0.31520511]
[0.11711455]
[0.31520511]
[0.29088603]
[0.19994726]
[0.31520511]
[0.31520511]
New features number of columns:  (16, 17)
sub data shape:  (15, 18)
[0.30119353]
[-0.12792606]
[-0.51330733]
[0.30119353]
[0.152056]
[0.23616014]
[-0.51330733]
[0.152056]
[0.30119353]
[0.32861051]
[0.32861051]
[0.152056]
[0.32861051]
[0.30119353]
[0.19702747]
[0.32861051]
[0.32861051]
New features number of colum

[0.48392521]
New features number of columns:  (15, 20)
sub data shape:  (14, 21)
[0.34328636]
[0.34328636]
[0.2770544]
[-0.48591053]
[0.34328636]
[0.34328636]
[0.31211563]
[0.34328636]
[0.34328636]
[0.34328636]
[0.34328636]
[0.31211563]
[0.2770544]
[0.2770544]
[0.34328636]
[0.31211563]
[0.31211563]
[0.34328636]
[0.34328636]
[0.31211563]
New features number of columns:  (14, 19)
sub data shape:  (13, 20)
[0.3594115]
[0.28301381]
[-0.45491028]
[0.3594115]
[0.39124356]
[0.3594115]
[0.39124356]
[0.3594115]
[0.39124356]
[0.39124356]
[0.32362864]
[0.28301381]
[0.28301381]
[0.39124356]
[0.3594115]
[0.32362864]
[0.3594115]
[0.3594115]
[0.32362864]
New features number of columns:  (13, 18)
sub data shape:  (13, 19)
[0.3594115]
[0.28301381]
[-0.45491028]
[0.3594115]
[0.3594115]
[0.39124356]
[0.3594115]
[0.39124356]
[0.39124356]
[0.32362864]
[0.28301381]
[0.28301381]
[0.39124356]
[0.3594115]
[0.32362864]
[0.3594115]
[0.3594115]
[0.32362864]
New features number of columns:  (13, 17)
sub data shape

[0.61938219]
[-0.0339445]
[-0.29438657]
[0.61938219]
[0.56938047]
[0.61938219]
[0.61938219]
[0.61938219]
[0.61938219]
[0.61938219]
[0.38424235]
[0.61938219]
[0.51414551]
[0.38424235]
[0.61938219]
[0.61938219]
[0.61938219]
[0.61938219]
[0.61938219]
[0.61938219]
New features number of columns:  (13, 24)
sub data shape:  (13, 25)
[0.56938047]
[0.58755013]
[0.56938047]
[0.56938047]
[0.58755013]
[-0.0339445]
[-0.29438657]
[0.61938219]
[0.56938047]
[0.61938219]
[0.61938219]
[0.61938219]
[0.61938219]
[0.61938219]
[0.38424235]
[0.61938219]
[0.51414551]
[0.38424235]
[0.61938219]
[0.61938219]
[0.61938219]
[0.61938219]
[0.61938219]
[0.61938219]
New features number of columns:  (13, 23)
sub data shape:  (13, 24)
[0.56938047]
[0.58755013]
[0.56938047]
[0.56938047]
[0.58755013]
[-0.0339445]
[-0.29438657]
[0.56938047]
[0.61938219]
[0.61938219]
[0.61938219]
[0.61938219]
[0.61938219]
[0.38424235]
[0.61938219]
[0.51414551]
[0.38424235]
[0.61938219]
[0.61938219]
[0.61938219]
[0.61938219]
[0.61938219]
[0.

[0.47897728]
[0.59959243]
[-0.01960182]
[0.08241638]
[0.59959243]
[0.40968225]
[0.05757065]
[-0.02400641]
[0.00630785]
[0.62649372]
[0.5714726]
[-0.16771251]
[0.65532806]
[0.65225295]
[0.08241638]
[0.65225295]
[-0.04388415]
[0.67694187]
[-0.01960182]
[-0.20295034]
[0.08241638]
[0.09278447]
[-0.07678259]
New features number of columns:  (28, 28)
sub data shape:  (28, 29)
[0.44514812]
[0.59959243]
[0.0071238]
[0.00764851]
[-0.07678259]
[0.5420534]
[0.47897728]
[0.59959243]
[-0.01960182]
[0.08241638]
[0.59959243]
[0.40968225]
[0.05757065]
[-0.02400641]
[0.00630785]
[0.62649372]
[0.5714726]
[-0.16771251]
[0.65532806]
[0.65225295]
[0.08241638]
[0.65225295]
[-0.04388415]
[-0.01960182]
[-0.20295034]
[0.08241638]
[0.09278447]
[-0.07678259]
New features number of columns:  (28, 27)
sub data shape:  (27, 28)
[0.38519026]
[0.53296186]
[-0.00771899]
[0.09502222]
[-0.10955307]
[0.47851279]
[0.41802003]
[0.53296186]
[-0.02162171]
[0.03623405]
[0.53296186]
[0.35045174]
[0.4490829]
[-0.0692399]
[-0.00

[-0.22944582]
[-0.29398505]
[0.13275195]
[0.66509109]
[-0.0870644]
[0.66294109]
[-0.20986891]
[0.61840861]
[-0.10929044]
[0.02238326]
[-0.10929044]
[0.65041552]
[-0.12184491]
[-0.21422833]
[-0.08433822]
[-0.00106485]
[-0.07107409]
[0.66509109]
[0.66509109]
[0.66294109]
[0.66294109]
[0.6410787]
[0.68403844]
[0.4913014]
[0.68403844]
[-0.0490255]
[-0.00057749]
[0.66294109]
[-0.17732844]
[0.66294109]
[0.68403844]
[0.54509216]
[-0.22944582]
New features number of columns:  (33, 32)
sub data shape:  (33, 33)
[-0.22944582]
[-0.29398505]
[0.13275195]
[0.66509109]
[-0.0870644]
[0.66294109]
[-0.20986891]
[0.61840861]
[-0.10929044]
[0.02238326]
[-0.10929044]
[0.65041552]
[-0.12184491]
[-0.21422833]
[-0.08433822]
[-0.00106485]
[-0.07107409]
[0.66509109]
[0.66509109]
[0.66294109]
[0.66294109]
[0.6410787]
[0.4913014]
[0.68403844]
[-0.0490255]
[-0.00057749]
[0.66294109]
[-0.17732844]
[0.66294109]
[0.68403844]
[0.54509216]
[-0.22944582]
New features number of columns:  (33, 31)
sub data shape:  (33, 3

[0.66808902]
[0.66808902]
[0.66808902]
[0.70246655]
[0.63175345]
[0.59329448]
New features number of columns:  (21, 33)
sub data shape:  (21, 34)
[0.66808902]
[0.63175345]
[0.63175345]
[0.63175345]
[-0.20659238]
[0.66808902]
[0.46342634]
[0.66808902]
[0.70246655]
[0.67342654]
[0.67342654]
[0.67342654]
[-0.01575992]
[-0.26222385]
[0.70246655]
[0.70246655]
[0.67342654]
[0.63175345]
[0.70246655]
[0.59329448]
[0.67342654]
[-0.08233856]
[0.70246655]
[0.66808902]
[0.70246655]
[-0.17750451]
[-0.01333873]
[0.66808902]
[0.66808902]
[0.66808902]
[0.70246655]
[0.63175345]
[0.59329448]
New features number of columns:  (21, 32)
sub data shape:  (21, 33)
[0.66808902]
[0.63175345]
[0.63175345]
[0.63175345]
[-0.20659238]
[0.66808902]
[0.46342634]
[0.66808902]
[0.67342654]
[0.67342654]
[0.67342654]
[-0.01575992]
[-0.26222385]
[0.70246655]
[0.70246655]
[0.67342654]
[0.63175345]
[0.70246655]
[0.59329448]
[0.67342654]
[-0.08233856]
[0.70246655]
[0.66808902]
[0.70246655]
[-0.17750451]
[-0.01333873]
[0.6680

[0.52970107]
[-0.26147684]
New features number of columns:  (12, 36)
sub data shape:  (12, 37)
[0.52970107]
[0.1908745]
[0.65002242]
[0.08363457]
[0.52970107]
[0.59301922]
[0.65002242]
[0.65002242]
[0.29038885]
[0.61339767]
[0.65002242]
[0.61339767]
[0.65002242]
[0.59301922]
[0.37959638]
[0.]
[0.65002242]
[0.65002242]
[0.65002242]
[0.65002242]
[0.52970107]
[0.65002242]
[0.65002242]
[0.4589713]
[0.4589713]
[0.59301922]
[0.37959638]
[0.65002242]
[-0.26147684]
[0.4589713]
[0.59301922]
[-0.16451404]
[0.65002242]
[0.59301922]
[0.52970107]
[-0.26147684]
New features number of columns:  (12, 35)
sub data shape:  (12, 36)
[0.52970107]
[0.1908745]
[0.08363457]
[0.52970107]
[0.59301922]
[0.65002242]
[0.65002242]
[0.29038885]
[0.61339767]
[0.65002242]
[0.61339767]
[0.65002242]
[0.59301922]
[0.37959638]
[0.]
[0.65002242]
[0.65002242]
[0.65002242]
[0.65002242]
[0.52970107]
[0.65002242]
[0.65002242]
[0.4589713]
[0.4589713]
[0.59301922]
[0.37959638]
[0.65002242]
[-0.26147684]
[0.4589713]
[0.59301922]

New features number of columns:  (19, 18)
sub data shape:  (18, 19)
[-0.42310723]
[-0.32088142]
[-0.02923497]
[0.3717755]
[0.1824014]
[-0.0680289]
[0.40884008]
[0.48532739]
[-0.02923497]
[-0.10893889]
[-0.12681295]
[-0.02923497]
[-0.02923497]
[0.3717755]
[0.3717755]
[0.47422726]
[-0.02420423]
[0.40884008]
New features number of columns:  (18, 17)
sub data shape:  (17, 18)
[0.30291637]
[0.28118527]
[0.16764038]
[0.23069965]
[0.08592951]
[0.20104612]
[0.25724537]
[-0.02528585]
[-0.18683934]
[0.23069965]
[0.16764038]
[0.16764038]
[0.23069965]
[0.23069965]
[0.30291637]
[-0.09784578]
[0.25724537]
New features number of columns:  (17, 16)
sub data shape:  (16, 17)
[0.31520511]
[0.16141672]
[0.2639319]
[0.11711455]
[0.23383585]
[0.29088603]
[-0.06897395]
[-0.27116853]
[0.23383585]
[0.19994726]
[0.16141672]
[0.23383585]
[0.2639319]
[0.31520511]
[-0.1590355]
[0.29088603]
New features number of columns:  (16, 15)
sub data shape:  (15, 16)
[0.19702747]
[0.30119353]
[0.09969593]
[0.23616014]
[0.30

[0.0186203]
[-0.05086909]
[0.3914821]
[0.34331915]
[0.47763211]
[0.47326383]
[0.47763211]
[0.49123734]
[0.47326383]
[-0.46528006]
[-0.37176028]
[0.49123734]
[0.47326383]
[0.47763211]
[0.49123734]
[-0.46528006]
[-0.03102172]
[0.47326383]
[0.0737285]
[0.34331915]
[0.34331915]
[0.0737285]
[0.22712152]
New features number of columns:  (28, 37)
sub data shape:  (28, 38)
[-0.35240398]
[-0.2632606]
[-0.00630034]
[0.47326383]
[0.02181438]
[0.45438399]
[0.3914821]
[-0.00630034]
[0.01000505]
[0.34331915]
[0.02764984]
[-0.46528006]
[-0.00630034]
[0.02181438]
[-0.00630034]
[0.0186203]
[-0.05086909]
[0.3914821]
[0.34331915]
[0.47763211]
[0.47326383]
[0.47763211]
[0.47326383]
[-0.46528006]
[-0.37176028]
[0.49123734]
[0.47326383]
[0.47763211]
[0.49123734]
[-0.46528006]
[-0.03102172]
[0.47326383]
[0.0737285]
[0.34331915]
[0.34331915]
[0.0737285]
[0.22712152]
New features number of columns:  (28, 36)
sub data shape:  (28, 37)
[-0.35240398]
[-0.2632606]
[-0.00630034]
[0.47326383]
[0.02181438]
[0.4543839

[0.33565092]
[0.36394302]
[0.40209461]
[0.3898973]
[0.3898973]
[0.41381685]
[0.33565092]
[0.40209461]
[0.3771921]
[0.32051618]
[0.01603716]
[0.40209461]
[-0.45083401]
[0.41381685]
[0.41381685]
[-0.25577641]
[-0.34479593]
New features number of columns:  (36, 38)
sub data shape:  (36, 39)
[0.35011049]
[-0.54855854]
[-0.1332073]
[5.55111512e-17]
[-0.54855854]
[0.3771921]
[0.40209461]
[-0.18676172]
[-0.54855854]
[0.16728653]
[0.3771921]
[0.36394302]
[-0.4442801]
[-0.1332073]
[0.3898973]
[0.27049826]
[-0.25577641]
[-0.34479593]
[0.40209461]
[0.40503915]
[0.32051618]
[0.33565092]
[0.36394302]
[0.40209461]
[0.3898973]
[0.3898973]
[0.41381685]
[0.33565092]
[0.40209461]
[0.3771921]
[0.32051618]
[0.01603716]
[0.40209461]
[-0.45083401]
[0.41381685]
[0.41381685]
[-0.25577641]
[-0.34479593]
New features number of columns:  (36, 37)
sub data shape:  (36, 38)
[0.35011049]
[-0.54855854]
[-0.1332073]
[5.55111512e-17]
[-0.54855854]
[0.3771921]
[0.40209461]
[-0.18676172]
[-0.54855854]
[0.16728653]
[0.37

[-0.23737852]
[0.41339002]
[0.42881096]
[0.41074459]
[-0.15586741]
[0.42375472]
[-0.05882091]
[0.42629312]
[0.42881096]
[-0.36670642]
[-0.00585281]
[0.4026732]
[0.02148422]
[0.08023997]
[0.18377003]
[0.11115181]
[0.27470916]
New features number of columns:  (171, 43)
sub data shape:  (171, 44)
[0.05884571]
[0.18309085]
[-0.00714457]
[0.42119551]
[0.06524232]
[0.06807572]
[0.1131439]
[0.1130361]
[0.11021044]
[-0.0232243]
[8.9947048e-05]
[-0.00812547]
[0.35898339]
[0.0191704]
[0.3123155]
[0.01100815]
[-0.00281876]
[0.35898339]
[-0.05369203]
[0.41861518]
[0.03597911]
[0.42629312]
[0.42375472]
[-0.37321015]
[0.42119551]
[0.42119551]
[0.4053865]
[-0.23737852]
[0.41339002]
[0.41074459]
[-0.15586741]
[0.42375472]
[-0.05882091]
[0.42629312]
[0.42881096]
[-0.36670642]
[-0.00585281]
[0.4026732]
[0.02148422]
[0.08023997]
[0.18377003]
[0.11115181]
[0.27470916]
New features number of columns:  (171, 42)
sub data shape:  (171, 43)
[0.05884571]
[0.18309085]
[-0.00714457]
[0.42119551]
[0.06524232]
[0.

sub data shape:  (103, 29)
[0.00530354]
[0.24715285]
[-0.00133997]
[-0.02351946]
[0.07862828]
[0.14763233]
[0.06135421]
[0.1247768]
[-0.25079245]
[-0.00130117]
[0.05550653]
[0.00346977]
[0.46643781]
[-0.00837498]
[-0.00130117]
[-0.04465187]
[0.04139551]
[-0.39305807]
[-0.38415438]
[-0.39305807]
[-0.0297492]
[-0.22034987]
[-0.06977355]
[0.0818286]
[-0.1941988]
[0.22352489]
[0.02681092]
[0.5235649]
New features number of columns:  (103, 27)
sub data shape:  (91, 28)
[-0.02040797]
[0.21340729]
[0.0067299]
[-0.06089902]
[0.03808966]
[0.16002747]
[-0.00362106]
[0.04433321]
[-0.32703744]
[-0.01556199]
[-0.02040797]
[0.01415454]
[0.50988298]
[0.02588914]
[0.00102114]
[-0.03367668]
[0.05410594]
[-0.34606787]
[-0.26218617]
[0.63889991]
[-0.0021658]
[-0.31594757]
[-0.04580665]
[0.09865306]
[-0.14925322]
[0.09242089]
[-0.33703449]
New features number of columns:  (91, 26)
sub data shape:  (90, 27)
[-0.03725091]
[0.53304302]
[0.01385135]
[-0.07827577]
[0.11191534]
[0.24804582]
[-0.02236685]
[0.194

[0.]
[0.]
[0.]
[-0.02484775]
[-0.18678479]
[-0.18678479]
[-0.09838082]
New features number of columns:  (10, 12)
sub data shape:  (10, 13)
[0.46299192]
[-0.02484775]
[-0.02484775]
[0.67160226]
[0.46299192]
[0.]
[0.]
[0.]
[-0.02484775]
[-0.18678479]
[-0.18678479]
[-0.09838082]
New features number of columns:  (10, 11)
sub data shape:  (9, 12)
[0.28658419]
[0.28658419]
[0.28658419]
[0.28658419]
[0.1824014]
[0.1824014]
[0.1824014]
[0.28658419]
[0.44286229]
[-0.27451944]
[-0.10893889]
New features number of columns:  (9, 10)
sub data shape:  (8, 11)
[0.27284141]
[0.27284141]
[0.27284141]
[0.38105884]
[0.13792538]
[0.27284141]
[0.13792538]
[0.27284141]
[0.54356444]
[-0.20643556]
New features number of columns:  (8, 9)
sub data shape:  (7, 10)
best feature index:  8 binary value: 0.0
New features number of columns:  (8, 9)
best feature index:  8 binary value: 1.0
best feature index:  8 binary value: 0.0
New features number of columns:  (9, 10)
best feature index:  8 binary value: 1.0
best fe

[0.12619293]
[0.21639693]
[-0.36590255]
[0.21564876]
[-0.42437258]
[0.20714844]
[-0.07536039]
[0.21261594]
[0.20635013]
[-0.05510959]
[0.21564876]
[0.21414045]
[0.0565378]
[0.21489661]
[0.21489661]
[0.2055474]
[-0.03302702]
[-0.28671973]
[0.04783493]
[0.0141496]
[0.06670199]
[0.07227755]
[0.01654643]
[-0.00605147]
New features number of columns:  (290, 43)
sub data shape:  (290, 44)
[0.06094751]
[0.02742714]
[0.00573952]
[0.21107496]
[-0.03090371]
[0.07227755]
[-0.00741483]
[0.06670199]
[0.01501124]
[0.07384172]
[0.03142496]
[0.16407437]
[0.20873194]
[0.01558755]
[0.03687507]
[0.00255353]
[-0.08447364]
[0.06461779]
[-0.10593569]
[0.20794236]
[0.12619293]
[-0.36590255]
[0.21564876]
[-0.42437258]
[0.20714844]
[-0.07536039]
[0.21261594]
[0.20635013]
[-0.05510959]
[0.21564876]
[0.21414045]
[0.0565378]
[0.21489661]
[0.21489661]
[0.2055474]
[-0.03302702]
[-0.28671973]
[0.04783493]
[0.0141496]
[0.06670199]
[0.07227755]
[0.01654643]
[-0.00605147]
New features number of columns:  (290, 42)
sub 

[0.05196402]
[0.08037686]
[0.05212874]
[0.00586957]
[-0.06880226]
[0.05732729]
[-0.09528381]
[-0.61356613]
[-0.52897252]
[-0.15614668]
[-0.11731903]
[0.11610548]
[-0.05281108]
[-0.52833766]
[0.10118439]
[-0.01317129]
[0.04659874]
[0.12033009]
[0.04993961]
[-0.06563704]
New features number of columns:  (137, 28)
sub data shape:  (104, 29)
[-0.03946802]
[0.1322337]
[0.05686696]
[0.05364203]
[0.11201756]
[-0.19677305]
[0.00955989]
[0.05307147]
[0.05475318]
[0.11548284]
[0.0286617]
[0.01825879]
[-0.07199419]
[-0.10877499]
[-0.07199419]
[-0.56358781]
[-0.47851829]
[-0.28188326]
[0.40802157]
[0.11691001]
[-0.04157315]
[-0.47747839]
[0.14941293]
[0.00770292]
[0.07179467]
[0.12418928]
[0.05307147]
[-0.10815599]
New features number of columns:  (104, 27)
sub data shape:  (100, 28)
[-0.02890123]
[0.13506746]
[0.05607283]
[0.06319735]
[0.10715402]
[-0.20774565]
[-0.02890123]
[0.05675053]
[0.0551307]
[0.12358849]
[0.02952765]
[0.01828465]
[-0.06858048]
[-0.09770776]
[-0.06858048]
[-0.5516883]
[-0.

[0.22308081]
[0.17392165]
[0.19977953]
[0.19977953]
[0.19977953]
[-0.47582951]
[0.26349783]
[-0.01722296]
[-0.01722296]
[0.19977953]
[0.07531644]
[0.22308081]
New features number of columns:  (19, 19)
sub data shape:  (17, 20)
[-0.02528585]
[-0.2976322]
[0.08592951]
[0.23069965]
[0.03498755]
[0.12964113]
[-0.18683934]
[0.28118527]
[0.23069965]
[0.20104612]
[0.25724537]
[0.20104612]
[-0.43348667]
[0.28118527]
[0.03498755]
[0.03498755]
[0.25724537]
[0.12964113]
[0.25724537]
New features number of columns:  (17, 18)
sub data shape:  (15, 19)
[-0.12792606]
[-0.38127733]
[0.03780052]
[0.27059596]
[-0.03665412]
[0.19702747]
[-0.24157796]
[0.23616014]
[0.19702747]
[0.27059596]
[0.19702747]
[-0.38127733]
[0.30119353]
[-0.03665412]
[0.03780052]
[0.30119353]
[0.152056]
[0.27059596]
New features number of columns:  (15, 17)
sub data shape:  (13, 18)
[-0.31513785]
[-0.31513785]
[0.11816382]
[0.28301381]
[-0.17041052]
[0.28301381]
[-0.17041052]
[0.23639485]
[0.18218032]
[0.28301381]
[0.18218032]
[-

[0.31659801]
[-0.15394455]
[0.27589629]
[-0.37676496]
[-0.15204693]
[-0.30709256]
[0.27355315]
[-0.00120194]
[0.3281228]
[0.12148965]
[0.32050357]
[-0.24921582]
[-0.35709314]
[0.32243203]
[-0.20178899]
[-0.51569978]
[0.24358982]
[0.32998889]
[-0.21291051]
[-0.24921582]
[0.03032496]
[0.10636822]
[0.32998889]
[0.31855897]
[-0.15204693]
[0.02177025]
[0.30447548]
[0.03978817]
[0.31462046]
[-0.05476162]
[0.32243203]
[0.31061465]
[-0.01955998]
New features number of columns:  (180, 41)
sub data shape:  (179, 42)
[0.29918007]
[-0.24786521]
[0.12197988]
[-0.37377564]
[0.02100318]
[-0.37744223]
[-0.37744223]
[0.32368434]
[-0.22428127]
[0.31779238]
[-0.1525971]
[0.27666499]
[-0.37537578]
[-0.15073622]
[-0.30573133]
[0.27429618]
[-0.00252544]
[0.3294309]
[0.12197988]
[0.32173681]
[-0.24786521]
[-0.35559845]
[0.32368434]
[-0.24786521]
[-0.55270539]
[0.24665954]
[-0.21155937]
[-0.30573133]
[0.03148535]
[0.1061904]
[0.33318407]
[0.32173681]
[-0.15073622]
[0.02084998]
[0.30554703]
[0.04092936]
[0.315

[-0.7510492]
[0.19493378]
[-0.21251284]
[0.21074303]
[0.03348235]
[0.2271278]
[0.1522487]
[0.2271278]
[0.20637658]
[0.22117638]
[0.22906329]
New features number of columns:  (129, 24)
sub data shape:  (125, 25)
[0.21261627]
[-0.65896089]
[0.02472477]
[-0.53988069]
[0.21261627]
[-0.37654653]
[-0.2555233]
[0.20060609]
[-0.32820738]
[0.2216507]
[-0.01610784]
[0.16493574]
[-0.45353997]
[-0.74501786]
[0.19810092]
[-0.20661068]
[0.21492056]
[0.03475341]
[0.2322969]
[0.15562003]
[0.23434587]
[0.21492056]
[0.22599173]
[0.23434587]
New features number of columns:  (125, 23)
sub data shape:  (121, 24)
[0.21926578]
[-0.65250109]
[0.02195005]
[-0.57089175]
[0.2168125]
[-0.36752432]
[-0.2839124]
[0.20400728]
[-0.32180795]
[0.22642463]
[-0.01728893]
[0.17219611]
[-0.44672861]
[-0.73865609]
[0.20133231]
[-0.23403703]
[0.22168505]
[0.03458555]
[0.23772969]
[0.16249992]
[0.21926578]
[0.23103715]
[0.23990278]
New features number of columns:  (121, 22)
sub data shape:  (117, 23)
[0.22378681]
[-0.64567809

best feature index:  1 binary value: 0.0
New features number of columns:  (116, 20)
sub data shape:  (2, 21)
best feature index:  1 binary value: 1.0
best feature index:  13 binary value: 0.0
New features number of columns:  (117, 21)
best feature index:  13 binary value: 1.0
best feature index:  22 binary value: 0.0
New features number of columns:  (121, 22)
sub data shape:  (4, 23)
best feature index:  22 binary value: 1.0
best feature index:  20 binary value: 0.0
New features number of columns:  (125, 23)
sub data shape:  (4, 24)
best feature index:  20 binary value: 1.0
best feature index:  12 binary value: 0.0
New features number of columns:  (129, 24)
sub data shape:  (4, 25)
best feature index:  12 binary value: 1.0
best feature index:  5 binary value: 0.0
New features number of columns:  (130, 25)
best feature index:  5 binary value: 1.0
best feature index:  5 binary value: 0.0
New features number of columns:  (131, 26)
best feature index:  5 binary value: 1.0
best feature inde

[0.01007566]
[0.09897857]
[-0.01006124]
[0.01158455]
[-0.00362017]
[0.04191063]
[-0.00380448]
[-0.01806436]
[-0.07175616]
[-0.07093778]
[0.13004003]
[-0.03644483]
[0.15811906]
[0.07116545]
[-0.40526186]
[0.16968033]
[-0.67756771]
[0.16899072]
[0.1640437]
[-0.19997134]
[0.17104716]
[-0.19227326]
[0.03487552]
[0.15581806]
[-0.02648405]
[-0.16840208]
[0.11487468]
[0.10828735]
[0.0068289]
[0.0025094]
New features number of columns:  (267, 37)
sub data shape:  (261, 38)
[0.00492165]
[-0.02494541]
[-0.03543802]
[-0.53298531]
[0.00767585]
[0.01255756]
[0.04570131]
[0.00904788]
[0.00769007]
[0.10457833]
[-0.01340011]
[0.01807551]
[-0.00603436]
[0.04027572]
[-0.00619075]
[-0.01477835]
[-0.08129246]
[-0.06750339]
[0.13407715]
[-0.03383102]
[0.16052359]
[0.07786943]
[-0.40194659]
[0.17258851]
[-0.67386075]
[0.17186962]
[0.16670977]
[-0.19631651]
[-0.18888297]
[0.03678543]
[0.15811903]
[-0.02381533]
[-0.16397007]
[0.12067387]
[0.11054436]
[0.00888038]
[0.00492165]
New features number of columns:  

[-0.16281752]
[0.22529486]
[0.16293372]
[0.22529486]
[0.37682239]
New features number of columns:  (17, 14)
sub data shape:  (15, 15)
best feature index:  3 binary value: 0.0
New features number of columns:  (17, 14)
sub data shape:  (2, 15)
best feature index:  3 binary value: 1.0
best feature index:  15 binary value: 0.0
New features number of columns:  (18, 15)
best feature index:  15 binary value: 1.0
best feature index:  2 binary value: 0.0
New features number of columns:  (21, 16)
sub data shape:  (3, 17)
best feature index:  2 binary value: 1.0
best feature index:  2 binary value: 0.0
New features number of columns:  (22, 17)
best feature index:  2 binary value: 1.0
best feature index:  0 binary value: 0.0
New features number of columns:  (25, 18)
sub data shape:  (3, 19)
best feature index:  0 binary value: 1.0
best feature index:  8 binary value: 0.0
New features number of columns:  (33, 19)
sub data shape:  (8, 20)
best feature index:  8 binary value: 1.0
best feature index: 

[-0.58461348]
[0.20902748]
[-0.0858703]
[-0.03257724]
[0.1934899]
[-0.13088987]
[-0.09562444]
[0.13598143]
[0.07203319]
[-0.11791559]
[-0.13915155]
New features number of columns:  (178, 43)
sub data shape:  (176, 44)
[0.03473862]
[0.01008586]
[-0.22773085]
[-0.01165633]
[0.00958031]
[0.0320237]
[0.01281237]
[-0.03249486]
[0.00177391]
[-0.03478419]
[-0.02904028]
[-0.15662609]
[-0.00151468]
[0.04433023]
[0.03473862]
[-0.12408772]
[-0.01193784]
[0.01445191]
[-0.02788355]
[0.20570896]
[-0.01616625]
[-0.02568252]
[-0.49232272]
[-0.41987887]
[0.20570896]
[0.20176398]
[-0.76638449]
[0.20440598]
[0.1166844]
[0.17871667]
[-0.36127921]
[-0.43706618]
[-0.69135233]
[0.21080493]
[-0.08409398]
[-0.03454122]
[0.19494009]
[-0.14157217]
[-0.09278227]
[0.13806631]
[0.07598049]
[-0.11504449]
[-0.13673409]
New features number of columns:  (176, 42)
sub data shape:  (173, 43)
[0.03739131]
[0.01004858]
[-0.22385883]
[-0.01296598]
[0.01004858]
[0.03048096]
[0.01075906]
[-0.02841648]
[0.00047473]
[-0.0338945

[0.07531644]
[-0.01722296]
[-0.01722296]
[0.19977953]
[-0.07621582]
[0.22308081]
[-0.07621582]
[-0.59726459]
[0.07531644]
[0.22308081]
[0.03259944]
[0.28118049]
[0.29747225]
[0.07531644]
[-0.34301048]
[0.11242089]
New features number of columns:  (19, 19)
sub data shape:  (18, 20)
best feature index:  16 binary value: 0.0
New features number of columns:  (19, 19)
best feature index:  16 binary value: 1.0
best feature index:  9 binary value: 0.0
New features number of columns:  (20, 20)
best feature index:  9 binary value: 1.0
best feature index:  1 binary value: 0.0
New features number of columns:  (21, 21)
best feature index:  1 binary value: 1.0
best feature index:  16 binary value: 0.0
New features number of columns:  (22, 22)
best feature index:  16 binary value: 1.0
best feature index:  23 binary value: 0.0
New features number of columns:  (23, 23)
best feature index:  23 binary value: 1.0
best feature index:  8 binary value: 0.0
New features number of columns:  (27, 24)
sub data 

[0.20117833]
[-0.39080057]
[-0.11194384]
[-0.11194384]
[0.16448891]
[0.20117833]
[-0.03855374]
[0.20472451]
[0.16905234]
[0.15978306]
[0.10293502]
[0.19753847]
[0.19753847]
[0.20117833]
[0.18195526]
[0.15492734]
[0.18601403]
[0.18601403]
[0.18195526]
[0.09601928]
[-0.01391398]
[0.139378]
[0.20117833]
[0.20117833]
[0.20117833]
[0.20472451]
[0.16905234]
[0.12215286]
New features number of columns:  (61, 41)
sub data shape:  (60, 42)
[0.16573816]
[-0.5549662]
[-0.04481563]
[-0.34778909]
[0.17503962]
[-0.66153874]
[0.20362907]
[0.13394858]
[-0.30917564]
[-0.72249103]
[-0.00848492]
[0.192062]
[0.19987743]
[-0.67919574]
[0.20362907]
[-0.38748184]
[-0.10902511]
[-0.10902511]
[0.17046027]
[0.20362907]
[-0.03630931]
[0.17503962]
[0.16086584]
[0.10176914]
[0.19987743]
[0.19987743]
[0.20362907]
[0.18379744]
[0.1558353]
[0.18798849]
[0.18798849]
[0.18379744]
[0.09454861]
[-0.0123359]
[0.13970497]
[0.20362907]
[0.20728264]
[0.20362907]
[0.2108423]
[0.17503962]
[0.12798367]
New features number of co

[-0.03802422]
[-0.09624915]
New features number of columns:  (290, 43)
sub data shape:  (283, 44)
[0.20136698]
[-0.03020133]
[-0.04591496]
[0.20047746]
[-0.68153936]
[-0.25202078]
[-0.24010467]
[-0.05495311]
[-0.42265608]
[0.03206904]
[0.1874468]
[-0.11688076]
[-0.70357749]
[0.07420299]
[-0.27799906]
[0.0502889]
[0.21492268]
[-0.16378604]
[-0.41011851]
[0.00835649]
[0.16449445]
[0.06367833]
[0.17742098]
[0.17216012]
[0.07722951]
[-0.01652181]
[0.21492268]
[0.02133855]
[-0.62597146]
[-0.01969296]
[0.19128389]
[-0.05981063]
[-0.23932895]
[0.20659631]
[-0.05269085]
[0.01428546]
[-0.05495311]
[-0.64658951]
[-0.37837788]
[-0.18470317]
[0.21411093]
[-0.04236782]
[-0.09524023]
New features number of columns:  (283, 42)
sub data shape:  (276, 43)
[0.20565803]
[-0.02658127]
[-0.04651282]
[0.20379822]
[-0.67693474]
[-0.27330968]
[-0.2354715]
[-0.06099168]
[-0.45649212]
[0.03384166]
[0.19011852]
[-0.13898979]
[-0.71190851]
[0.07334116]
[-0.30254977]
[0.05345479]
[-0.15946038]
[-0.43982085]
[0.010

[0.03842951]
[-0.50531389]
[-0.28177829]
[-0.38827434]
[-0.55129743]
New features number of columns:  (126, 27)
sub data shape:  (110, 28)
[-0.25007269]
[-0.2068086]
[-0.71920843]
[-0.52344168]
[-0.05839248]
[-0.63151692]
[-0.01426709]
[-0.52344168]
[-0.66628886]
[-0.10754221]
[-0.30233292]
[0.]
[-0.30293848]
[0.04452726]
[0.19694356]
[0.19694356]
[0.21048436]
[-0.02425989]
[-0.04566418]
[0.23214599]
[-0.52344168]
[-0.49943351]
[0.04397137]
[-0.50830819]
[-0.30233292]
[-0.3606304]
[-0.52344168]
New features number of columns:  (110, 26)
sub data shape:  (97, 27)
[-0.30392886]
[-0.19867139]
[-0.69164454]
[-0.60481689]
[-0.04926976]
[-0.60327135]
[-0.00990011]
[-0.49544722]
[-0.57396288]
[-0.08289479]
[-0.27497447]
[-0.01281604]
[-0.33829517]
[0.04762754]
[0.2127866]
[0.21715446]
[0.23381726]
[-0.01281604]
[-0.02345464]
[-0.60481689]
[-0.52311899]
[0.0490173]
[-0.51378522]
[-0.33297636]
[-0.33297636]
[-0.49544722]
New features number of columns:  (97, 25)
sub data shape:  (80, 26)
[-0.25

[-0.06336821]
[0.0047396]
[-0.21199535]
[-0.18968488]
[0.16705739]
[0.14638289]
[-0.52322541]
[-0.15261652]
[-0.09928634]
New features number of columns:  (116, 49)
sub data shape:  (116, 50)
[-0.1106176]
[0.16385808]
[-0.02857873]
[-0.10435242]
[-0.26701043]
[-0.81175993]
[-0.30141573]
[-0.17003685]
[-0.39074229]
[-0.39074229]
[-0.08650922]
[0.16056645]
[0.15368812]
[0.16385808]
[-0.52322541]
[0.15544609]
[0.16056645]
[-0.0764142]
[-0.22934267]
[0.17319556]
[0.17169236]
[-0.81175993]
[0.1259378]
[0.13243153]
[0.16546901]
[0.16056645]
[0.15009155]
[0.17319556]
[0.14059684]
[0.16385808]
[-0.01686231]
[0.16546901]
[0.1425563]
[0.17210477]
[0.16385808]
[0.15368812]
[0.12813957]
[0.13658144]
[0.16222408]
[0.16222408]
[-0.06336821]
[0.0047396]
[-0.21199535]
[-0.18968488]
[0.16705739]
[0.14638289]
[-0.52322541]
[-0.15261652]
[-0.09928634]
New features number of columns:  (116, 48)
sub data shape:  (116, 49)
[-0.1106176]
[0.16385808]
[-0.02857873]
[-0.10435242]
[-0.26701043]
[-0.81175993]
[-0

[-0.39226339]
[0.08344171]
[0.0863855]
[-0.78691513]
[-0.31342654]
[-0.31342654]
New features number of columns:  (80, 33)
sub data shape:  (77, 34)
[0.08546719]
[0.06690523]
[-0.07199596]
[0.09314438]
[0.09167949]
[-0.66913286]
[-0.07199596]
[0.09167949]
[0.09018065]
[-0.06362495]
[-0.15149799]
[0.0803971]
[0.07679652]
[0.09457658]
[0.09597724]
[0.09018065]
[0.08212944]
[0.09597724]
[0.07679652]
[0.09314438]
[0.08212944]
[0.08707591]
[0.07862009]
[0.08707591]
[0.09167949]
[-0.2037346]
[-0.02282056]
[-0.38708927]
[0.08546719]
[0.08864658]
[-0.78251713]
[-0.34443499]
[-0.34443499]
New features number of columns:  (77, 32)
sub data shape:  (74, 33)
[0.08758386]
[0.0696126]
[-0.0655643]
[0.09589091]
[0.09430907]
[-0.77779254]
[-0.08418139]
[0.09430907]
[0.09268901]
[-0.0655643]
[-0.1610874]
[0.0857948]
[0.08395897]
[0.09894568]
[0.09268901]
[0.08758386]
[0.10042127]
[0.07815011]
[0.09589091]
[0.08758386]
[0.09102921]
[0.08013884]
[0.08932806]
[0.09430907]
[-0.1977241]
[-0.02209061]
[-0.38

[0.1625388]
[0.18536516]
[0.19798367]
[0.17998497]
[0.20037566]
[0.00615375]
[0.16858603]
[0.1905495]
[-0.57549894]
[0.16858603]
[0.19554948]
[0.17439647]
[0.18536516]
[0.20037566]
[0.08448604]
[0.1242321]
[-0.42821623]
[-0.10537685]
[0.165593]
[0.18536516]
[-0.12740162]
[0.13563153]
[-0.7531117]
[-0.35158055]
[0.19307186]
[-0.06966546]
[0.19798367]
[0.1827003]
[0.1905495]
[-0.56869498]
[0.17721758]
[0.17439647]
[-0.05414666]
[0.16858603]
[0.19798367]
[0.20272666]
[0.17439647]
[0.20272666]
[-0.28313814]
New features number of columns:  (92, 42)
sub data shape:  (90, 43)
[0.19339465]
[0.20113914]
[-0.03072476]
[0.15412183]
[0.16413113]
[0.18798849]
[0.20113914]
[0.18520786]
[0.20362907]
[0.00632868]
[0.17352859]
[0.19339465]
[-0.57146124]
[0.17046027]
[0.19860434]
[0.17948318]
[0.18798849]
[0.20362907]
[0.08702493]
[0.13198405]
[-0.45593478]
[-0.11147476]
[0.16732851]
[0.19071688]
[-0.13506045]
[0.13970497]
[-0.74877555]
[-0.34755619]
[0.19602331]
[-0.06549446]
[0.20113914]
[0.18798849]

[0.06237764]
[0.22460942]
[0.22460942]
[0.21880166]
[0.14721943]
[0.19341906]
[-0.43280197]
[-0.28445621]
[0.18646783]
[0.21880166]
[-0.20903373]
[0.16389881]
[-0.61605106]
[-0.03154624]
[0.23022552]
[-0.61605106]
[0.22460942]
[0.23022552]
[-0.0511983]
[0.19341906]
[0.17924309]
[-0.55982887]
New features number of columns:  (49, 26)
sub data shape:  (46, 27)
[0.22066254]
[0.20628436]
[0.24031935]
[0.22066254]
[0.21361154]
[0.04490434]
[0.23400167]
[0.24031935]
[0.22745413]
[0.1648013]
[0.20628436]
[-0.41216761]
[-0.30696854]
[0.19072662]
[0.22745413]
[-0.22243269]
[0.18245414]
[-0.60038831]
[-0.02692569]
[-0.60038831]
[0.24031935]
[0.24031935]
[-0.02692569]
[0.19866272]
[0.18245414]
[-0.54049945]
New features number of columns:  (46, 25)
sub data shape:  (43, 26)
[0.2514084]
[0.22905822]
[0.22905822]
[0.23679979]
[0.02053148]
[0.2514084]
[0.25831081]
[0.23679979]
[0.1946812]
[0.22905822]
[-0.51877194]
[-0.38895307]
[0.20383581]
[0.2442437]
[-0.28264825]
[0.1946812]
[-0.5828391]
[0.0004

sub data shape:  (70, 49)
[0.09055297]
[-0.3734196]
[-0.0853136]
[-0.26240998]
[-0.21056085]
[-0.21056085]
[0.09807047]
[0.09055297]
[-0.26240998]
[0.00447115]
[0.09807047]
[0.09055297]
[0.10486374]
[0.10155038]
[0.07992894]
[-0.0853136]
[-0.3305305]
[0.10486374]
[-0.12192335]
[0.10155038]
[-0.86340538]
[-0.13634993]
[-0.0253477]
[0.03573994]
[0.09983209]
[0.03948914]
[0.09807047]
[-0.06521791]
[0.04989794]
[0.00447115]
[0.10486374]
[0.08648182]
[0.09626373]
[0.09626373]
[0.09807047]
[0.08217644]
[0.10646197]
[0.10646197]
[0.08217644]
[0.10155038]
[0.0277649]
[0.08217644]
[0.09983209]
[-0.56233861]
[0.09626373]
[0.09440994]
[0.08435976]
[0.02351676]
New features number of columns:  (70, 47)
sub data shape:  (69, 48)
[0.09132197]
[-0.37125676]
[-0.08285023]
[-0.2917395]
[-0.20824529]
[-0.23256299]
[0.09906009]
[0.09132197]
[-0.26014654]
[0.00707218]
[0.09906009]
[0.09132197]
[0.10604195]
[0.10263786]
[0.08036405]
[-0.08285023]
[-0.37125676]
[0.10604195]
[-0.13395141]
[0.10263786]
[-0.86

[0.0494987]
[-0.00907925]
[0.05269935]
[-0.03693317]
[0.05565716]
[0.06012245]
[0.05565716]
[-0.08124144]
[0.05420671]
[0.01741259]
[0.05659418]
[0.06012245]
[0.05320835]
[0.05969955]
[0.05883871]
[-0.19782552]
New features number of columns:  (143, 55)
sub data shape:  (143, 56)
[0.0494987]
[-0.31896851]
[-0.21045747]
[0.03658599]
[0.05565716]
[0.05840057]
[0.05795716]
[0.05659418]
[0.03878632]
[0.05840057]
[0.03949629]
[0.05420671]
[0.05705407]
[0.05883871]
[0.05750836]
[0.05795716]
[0.05420671]
[0.04662173]
[0.06012245]
[-0.10090105]
[0.06012245]
[0.06012245]
[0.06012245]
[-0.27476545]
[-0.25617122]
[-0.1064872]
[-0.21045747]
[-0.23942887]
[-0.29555352]
[-0.23942887]
[0.05269935]
[-0.83890844]
[-0.2242648]
[-0.25617122]
[-0.00402504]
[0.06012245]
[0.0185129]
[-0.25617122]
[0.05795716]
[0.0494987]
[-0.00907925]
[0.05269935]
[-0.03693317]
[0.05565716]
[0.06012245]
[0.05565716]
[-0.08124144]
[0.05420671]
[0.01741259]
[0.05659418]
[0.06012245]
[0.05320835]
[0.05969955]
[0.05883871]
[-0.